export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PREPARING: 'PREPARING',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export const CLAIM_TYPE = {
  RETURN: 'RETURN',
  EXCHANGE: 'EXCHANGE',
  CANCEL: 'CANCEL'
} as const

export const CLAIM_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  REFUNDED: 'REFUNDED',
  COMPLETED: 'COMPLETED'
} as const

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  WITHDRAWN: 'WITHDRAWN'
} as const

export const USER_ROLE = {
  USER: 'USER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN'
} as const

export const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISCONTINUED: 'DISCONTINUED'
} as const

export const BANNER_POSITION = {
  MAIN_TOP: 'MAIN_TOP',
  MAIN_MIDDLE: 'MAIN_MIDDLE',
  MAIN_BOTTOM: 'MAIN_BOTTOM',
  CATEGORY: 'CATEGORY'
} as const

export const NOTICE_TYPE = {
  NOTICE: 'NOTICE',
  INSPECTION: 'INSPECTION',
  GUIDELINES: 'GUIDELINES',
  EVENT: 'EVENT'
} as const

export const INQUIRY_STATUS = {
  PENDING: 'PENDING',
  ANSWERED: 'ANSWERED'
} as const
